name: Notifying

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

concurrency:
  group: notifying-${{ github.ref }}
  cancel-in-progress: true

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Post updates
      run: |
        DAY_OFFSET=15
        DATE_TODAY=$(date --date="$((-$DAY_OFFSET)) day" +'%Y-%m-%d')
        DATE_YESTERDAY=$(date --date="$((-$DAY_OFFSET - 1)) day" +'%Y-%m-%d')

        TODAY_COMMIT=$(git rev-list -n 1 --first-parent --before="$DATE_TODAY 00:00:00" staging)
        PREVIOUS_COMMIT=$(git rev-list -n 1 --first-parent --before="$DATE_YESTERDAY 00:00:00" staging)

        if [ ! -z "$TODAY_COMMIT" ]; then
          echo "Checking files changed between $PREVIOUS_COMMIT and $TODAY_COMMIT..."

          ADDED_FILES=$(git diff --name-only --diff-filter=A $PREVIOUS_COMMIT $TODAY_COMMIT | grep \.md$)
          MODIFIED_FILES=$(git diff --name-only --diff-filter=M $PREVIOUS_COMMIT $TODAY_COMMIT | grep \.md$)

          ADDED_JSONS=()
          MODIFIED_JSONS=()

          while IFS='' read -r -d '' filename; do
            if [ -f "$filename" ]; then
              FILEPATH=${filename#"docs/"}
              FILEPATH=${FILEPATH%".md"}
              FILEPATH=${FILEPATH/ /"%20"}
              TITLE=$(basename filename)
              TITLE=${TITLE%".md"}
              URL="https://nobrainergames.com/$FILEPATH/"
              ADDED_JSONS+=("{\"title\":\"$TITLE\",\"url\":\"$URL\",\"color\":\"65280\"}")
            fi
          done < <(printf "%s\0" "$ADDED_FILES" | tr "\n" "\0")

          while IFS='' read -r -d '' filename; do
            if [ -f "$filename" ]; then
              FILEPATH=${filename#"docs/"}
              FILEPATH=${FILEPATH%".md"}
              FILEPATH=${FILEPATH/ /"%20"}
              TITLE=$(basename filename)
              TITLE=${TITLE%".md"}
              URL="https://nobrainergames.com/$FILEPATH/"
              MODIFIED_JSONS+=("{\"title\":\"$TITLE\",\"url\":\"$URL\",\"color\":\"16776960\"}")
            fi
          done < <(printf "%s\0" "$MODIFIED_FILES" | tr "\n" "\0")

          echo "Found ${#ADDED_JSONS[@]} added files and ${#MODIFIED_JSONS[@]} modified files."

          ALL_JSONS=(${ADDED_JSONS[@]})
          ALL_JSONS+=(${MODIFIED_JSONS[@]})

          EMBEDS=$(printf ",%s" "${ALL_JSONS[@]}")
          EMBEDS=${EMBEDS:1}

          BODY="{\"username\": \"No Brainer Games\",\
            \"content\": \"Published ${#ADDED_JSONS[@]} new pages and changed ${#MODIFIED_JSONS[@]} pages.\",\
            \"embeds\": [$EMBEDS]}"

          echo "Sending payload '$BODY' to Discord server..."

          curl -H "Content-Type: application/json" -d "$BODY" "${{ secrets.DISCORD_SITE_UPDATES_WEBHOOK }}"
        fi
