name: Notifying

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

concurrency:
  group: notifying-${{ github.ref }}
  cancel-in-progress: true

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Post updates
      run: |
        echo "It is now $(date + '%Y-%m-%d %H:%M:%S')."

        DAY_OFFSET=0
        DATE_TODAY=$(date --date="$((-$DAY_OFFSET)) day" +'%Y-%m-%d')
        DATE_YESTERDAY=$(date --date="$((-$DAY_OFFSET - 1)) day" +'%Y-%m-%d')

        echo "Looking for commits between $DATE_TODAY and $DATE_YESTERDAY..."

        TODAY_COMMIT=$(git rev-list -n 1 --first-parent --before="$DATE_TODAY 00:00:00" staging)
        PREVIOUS_COMMIT=$(git rev-list -n 1 --first-parent --before="$DATE_YESTERDAY 00:00:00" staging)

        if [ ! -z "$TODAY_COMMIT" ]; then
          echo "Checking files changed between $PREVIOUS_COMMIT and $TODAY_COMMIT..."

          ADDED_FILES=$(git diff --name-only --diff-filter=A $PREVIOUS_COMMIT $TODAY_COMMIT | { grep \.md$ || true; })
          MODIFIED_FILES=$(git diff --name-only --diff-filter=M $PREVIOUS_COMMIT $TODAY_COMMIT | { grep \.md$ || true; })

          ADDED_JSONS=()
          MODIFIED_JSONS=()
          ALL_JSONS=()

          while IFS='' read -r -d '' filename; do
            if [ -f "$filename" ]; then
              FILEPATH=${filename#"docs/"}
              FILEPATH=${FILEPATH%".md"}
              TITLE="$FILEPATH"
              FILEPATH=${FILEPATH// /"%20"}
              URL="https://nobrainergames.com/$FILEPATH/"
              ADDED_JSONS+=("{\"title\":\"$TITLE\",\"url\":\"$URL\",\"color\":\"65280\"}")
              ALL_JSONS+=(${ADDED_JSONS[-1]})
            fi
          done < <(printf "%s\0" "$ADDED_FILES" | tr "\n" "\0")

          echo "Found ${#ADDED_JSONS[@]} added files."

          while IFS='' read -r -d '' filename; do
            if [ -f "$filename" ]; then
              FILEPATH=${filename#"docs/"}
              FILEPATH=${FILEPATH%".md"}
              TITLE="$FILEPATH"
              FILEPATH=${FILEPATH// /"%20"}
              URL="https://nobrainergames.com/$FILEPATH/"
              MODIFIED_JSONS+=("{\"title\":\"$TITLE\",\"url\":\"$URL\",\"color\":\"16776960\"}")
              ALL_JSONS+=(${MODIFIED_JSONS[-1]})
            fi
          done < <(printf "%s\0" "$MODIFIED_FILES" | tr "\n" "\0")

          echo "Found ${#MODIFIED_JSONS[@]} modified files."

          if [ ${#ALL_JSONS[@]} -ne 0 ]; then
            EMBEDS=$(IFS=, ; echo "${ALL_JSONS[*]}")

            BODY="{\"username\": \"No Brainer Games\",\
                   \"content\": \"New content added to https://nobrainergames.com\",\
                   \"embeds\": [$EMBEDS]}"

            echo "Sending payload '$BODY' to Discord server..."

            curl -H "Content-Type: application/json" -d "$BODY" "${{ secrets.DISCORD_SITE_UPDATES_WEBHOOK }}"
          fi
        fi
